version: '3.8'

# Configual parameters for the services.
x-environment: &enviroment_vars
  POSTGRES_USER: energy
  POSTGRES_PASSWORD: energy
  POSTGRES_DB: energy
  POSTGRES_HOST: postgres-db  # Do not change. Need to med the same as the service name for the postgres image
  DATABASE_USER: energy
  DATABASE_PASS: energy
  DATABASE_NAME: energy
  DATABASE_HOST: postgres-db  # Do not change. Need to med the same as the service name for the postgres image


services:
  redis-db:
    image: arm32v7/redis
    restart: always
    container_name: redis-db
    networks:
      - front-end
      - back-end

  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-db
    networks:
      - front-end
      - back-end
    environment: *enviroment_vars
    volumes:
      - energy-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: postgres-adm
    ports:
      - 8080:8080
    networks:
      - back-end

  energy-webhook:
    container_name: webhook
    image: sbv1307/energy-webhook
    restart: always
# During development mount volume! In production, files are copied into the webhook image
    volumes:
      - ./energy-webhook/www/:/var/www/html/
    environment: *enviroment_vars
    links:
      - redis-db
    ports:
      - 8880:80
    depends_on:
      - redis-db
    networks:
      - front-end
  
  energy-worker:
    container_name: energy-worker
    image: sbv1307/energy-worker 
    restart: always
# During development mount volume! In production, files are copied into the worker image
    volumes:
      - ./energy-worker/python:/usr/src/app
    environment: *enviroment_vars
    links:
      - redis-db
      - postgres-db
    depends_on:
      - redis-db
      - postgres-db
    networks:
      - back-end

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    environment: *enviroment_vars
    volumes:
      - energy-grafana-data:/var/lib/grafana
    ports:
      - 3500:3000
    depends_on:
      - postgres-db
    networks:
      - back-end
      

networks:
  front-end:
    name: Fron-end
  back-end:
    name: back-end

volumes:
  energy-grafana-data:
    name: grafana-data
  energy-db:
    name: energy-db
