# Docker-compose file for building the "Energianalyse" program stack.

version: '3.8'

# Configual parameters for the services. This is just a way to group these settings an mage changes easy
# POSTGRES... environemtn variables are used in the postgres-db, energy-webhook and energy-worker services.
# DATABASE... environment variables are used in the grafana service
x-environment: &enviroment_vars
  POSTGRES_USER: energy                 # Decide you own username
  POSTGRES_PASSWORD: energy             # Be aware of using special characteres.
                                        # Special characters might be interpreted in various ways be the OS. 
  POSTGRES_DB: energy                   # Decite you own database name
  POSTGRES_HOST: postgres-db  # Do not change. Need to med the same as the service name for the postgres image

  DATABASE_USER: energy                 # Specify the same name as for POSTGRES_USER
  DATABASE_PASS: energy                 # Specify the same name as for POSTGRES_PASSWORD
  DATABASE_NAME: energy                 # Specify the same name as for POSTGRES_DB
  DATABASE_HOST: postgres-db  # Do not change. Need to med the same as the service name for the postgres image

  GOOGLE_WEBHOOK_URL: http://192.168.10.102/energyRegistrations/updateEnergyRegistrations
  GOOGLE_WEBHOOK: test

services:
  redis-db:
    image: arm32v7/redis
    restart: always
    container_name: redis-db
    networks:
      - front-end
      - back-end
    volumes:
      - redis-data:/data

  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-db
    networks:
      - front-end
      - back-end
    environment: *enviroment_vars
    volumes:
      - energy-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: postgres-adm
    ports:
      - 8080:8080
    networks:
      - back-end

  mosquitto-mqtt:
    container_name: mosquitto-mqtt
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - front-end

  energy-webhook:
    container_name: energy-webhook
    image: sbv1307/energy-webhook
    restart: always
    environment: *enviroment_vars
    links:
      - redis-db
    ports:
      - 8880:80
    depends_on:
      - redis-db
      - energy-worker
      - mosquitto-mqtt
    networks:
      - front-end
#    volumes:      #v Verify that this is located under the energy-webhook service !!!!!!!
#      - ./energy-webhook/www:/var/www

  energy-mqtthook:
    container_name: energy-mqtthook
    image: energy-mqtthook
    restart: always
    environment:      # Set environment variables: Se more info in main README.md
      - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
      - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
    links:
      - redis-db
    depends_on:
      - redis-db
      - energy-worker
      - mosquitto-mqtt
    networks:
      - front-end
    volumes:    # Verify that his i located under the energy-mqtthook service !!!!!
      - ./energy-mqtthook/usr/src/mqtt:/usr/src/mqtt
    
  energy-worker:
    container_name: energy-worker
    image: sbv1307/energy-worker 
    restart: always
    environment: *enviroment_vars
    links:
      - redis-db
      - postgres-db
    depends_on:
      - redis-db
      - postgres-db
    networks:
      - back-end
#    volumes:      #v Verify that this is located under the energy-worker service !!!!!!!
#      - ./energy-worker/python:/usr/src/app

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    environment: *enviroment_vars
    volumes:
      - energy-grafana-data:/var/lib/grafana
    ports:
      - 3500:3000
    depends_on:
      - postgres-db
    networks:
      - back-end
      

networks:
  front-end:
    name: Fron-end
  back-end:
    name: back-end

volumes:
  redis-data:
    name: redis-data
  energy-grafana-data:
    name: grafana-data
  energy-db:
    name: energy-db
  mosquitto-conf:
    name: mosquitto-conf
  mosquitto-data:
    name: mosquitto-data
  mosquitto-log:
    name: mosquitto-log
